name: weather
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.8.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  http: ^1.1.0
  intl: ^0.18.1
  location: ^5.0.3
  lottie: ^2.6.0
  provider: ^6.0.5
  vibration: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - Assets/
